### ISSUE TITLE
Single quotes in payload data break initial payload

### ISSUE THREAD

**Issue by BrentChesny** [elipZis/inertia-echo#1]
If one of the inertia props contains a single quote, the initial non-async page load fails because the json only get parsed partially from the data attribute.

<img width="639" alt="Screenshot 2021-02-15 at 22 00 28" src="https://user-images.githubusercontent.com/1449435/107992626-5e8fc980-6fd9-11eb-9d38-4ac24514d356.png">
<img width="1203" alt="Screenshot 2021-02-15 at 22 00 55" src="https://user-images.githubusercontent.com/1449435/107992628-60598d00-6fd9-11eb-85e7-b7e3c1bcbeef.png">

**Comment by nea** [comment]
Ahoi @BrentChesny 

Sorry about that, probably forgot to escape correctly.

Will look into it.


Thanks

**Comment by ironytr** [comment]
for quick fix im used this (im noob on programming), Author already created a method for it.
in app html instead of {{intertia .page}} use this just now hope for to fix.
`    <div id='app' data-page='{{json_encode_raw .page}}'></div>
`

**Comment by BrentChesny** [comment]
@ironytr The `inertia` template function uses the same logic as `json_encode_raw` under the hood, so I'm not sure this actually fixes the issue?

**Comment by ironytr** [comment]
in my case its fixed. in your shared picture im seeing normal json response but this function transform it html json format which is example `    <div id='app' data-page='{&#34;component&#34;:&#34;Category/Index&#34;,&#34;host&#34;:&#34;localhost:9001&#34;,&#34;method&#34;:&#34;GET&#34;,&#34;path&#34;:&#34;/app/categories&#34;,&#34;props&#34;:{&#34;categories&#34;:{&#34;data&#34;:[{&#34;ID&#34;:28,&#34;CreatedAt&#34;:&#34;0001-01-01T03:00:00&#43;03:00&#34;,&#34;UpdatedAt&#34;:&#34;2021-03-27T11:19:42.136444&#43;03:00&#34;,&#34;DeletedAt&#34;:null,&#34;Name&#34;:&#34;ne&#34;,&#34;ParentID&#34;:3,&#34;StoreID&#34;:&#34;26e9afa1-cf04-45ff-a8f0-79ce5b53b3a3&#34;,&#34;Status&#34;:false,&#34;Paths&#34;:&#34;Küçük\u003eBüyük\u003eOluştur\u003ene&#34;,&#34;Params&#34;:{&#34;n11&#34;:{&#34;id&#34;:0,&#34;path&#34;:&#34;&#34;},&#34;pttavm&#34;:{&#34;id&#34;:0,&#34;path&#34;:&#34;&#34;},&#34;trendyol&#34;:{&#34;id&#34;:3719,&#34;path&#34;:&#34;Elektronik\u003eTelefon\u003eAkıllı Cep Telefonu&#34;},&#34;hepsiburada&#34;:{&#34;id&#34;:0,&#34;path&#34;:&#34;&#34;}},&#34;Defaults&#34;:{&#34;n11&#34;:{&#34;id&#34;:0,&#34;name&#34;:&#34;&#34;},&#34;pttavm&#34;:{&#34;id&#34;:0,&#34;name&#34;:&#34;&#34;},&#34;trendyol&#34;:[{&#34;Default&#34;:{&#34;ID&#34;:4295,&#34;Name&#34;:&#34;Kadın / Kız&#34;,&#34;TrendyolCategoryAttributeID&#34;:343},&#34;Attribute&#34;:{&#34;id&#34;:343,&#34... vs vs vs ..... 34;StoreID&#34;:&#34;26e9afa1-cf04-45ff-a8f0-79ce5b53b3a3&#34;,&#34;CurrentTeamID&#34;:&#34;3ccee3c5-298c-43d5-bbaf-f17f3680af89&#34;}},&#34;scheme&#34;:&#34;http&#34;,&#34;status&#34;:200,&#34;url&#34;:&#34;/app/categories&#34;,&#34;version&#34;:&#34;&#34;}'></div>
`
sorry for bad english

**Comment by BrentChesny** [comment]
Ah you're right, the `inertia` function wraps it in `template.HTML` which causes it not to be escaped.

**Comment by nea** [comment]
Ahoi you two

I am really sorry I am slow atm, overloaded with work.

Thanks a lot for the suggestion and PR. I will merge it so that this is fixed for now.

As soon as I have more time I will drop in again.


Cheers

**Comment by ironytr** [comment]
> Ahoi you two
> 
> I am really sorry I am slow atm, overloaded with work.
> 
> Thanks a lot for the suggestion and PR. I will merge it so that this is fixed for now.
> 
> As soon as I have more time I will drop in again.
> 
> Cheers

Thank you for this great package, its mean alot for me and im learning alot by your beatifull code. some of other bugs already have but im not capable of reporting it. for  what other bugs i remember; 1: when errors occoured its just returning 1 error instead of all ( ErrorResponse(c, err));

2:  redirect is not working this -> return controller.AddSuccessFlash(c, "Üretici Başarıyla Oluşturuldu.").Redirect(c, "/app/trendyols", http.StatusFound, "GET"), instead of this for quick fix im using
 `controller.AddSuccessFlash(c, "Eşleşme başarılı")
	c.Request().Method = "GET"
	http.Redirect(c.Response(),c.Request(),"/app/trendyol",http.StatusSeeOther)`

maybe these bugs my coding skill problems. 
thank you, have a great day.
